config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'users#index'
  
 

  resources :users
  get '/nonprofits/:id/profile' => 'nonprofits#profile', as: :profile
  
  post 'nonprofits' => 'donations#create', as: :donate
  post 'nonprofits/new' => 'nonprofits#create', as: :new_nonprofit_path
  resources :nonprofits

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :donations
  has_many :nonprofits, through: :donations	
  has_many :topicJunctionTables
  has_many :topics, through: :topicJunctionTables
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :omniauthable, :omniauth_providers => [:stripe_connect]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #THIS SHOULD BE IN THE NONPROFIT MODEL! 
  def interested 
  	nonprofits = []
  	self.topics.each do |a|
  	  TopicJunctionTable.where(topic_id: a.id).where.not(nonprofit_id: nil).each do |a|
  	  	nonprofit = Nonprofit.find(a.nonprofit_id)
        if nonprofits != [] && nonprofits.include?(nonprofit) == false
  	  	  nonprofits << nonprofit
        elsif nonprofits == []
          nonprofits << nonprofit 
        end
  	  end
  	end
  	return nonprofits

  end      

  #NORMALIZE NAME
  def name
    return (self.first_name.capitalize + " " + self.last_name.capitalize)
  end




end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  def stripe_connect
    raise "STOP"
  end


  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  
   #def new
    #  super


   #end

  # POST /resource
   
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #    devise_parameter_sanitizer.for(:sign_up) << :topic
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
     edit_user_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if user_signed_in?
      redirect_to user_path(current_user)
    end


  end

  # GET /users/1
  # GET /users/1.json
  def show
    if user_signed_in? && User.find(params[:id]) == current_user
      @topics = []
      @topics_by_num = []
      @user.nonprofits.each do |n|
        @topics << n.main 
      end

      @topics.each do |a|
        @topics_by_num << { 'topic' => a, 'donations' => @topics.count(a)} if !@topics_by_num.include?({  'topic' => a, 'donations' => @topics.count(a)})
      end

      respond_to do |format|
          format.html {@user = User.find(params[:id])}
          format.json { render :json => {data: @topics_by_num} }

      end
    else
       redirect_to users_path
    end 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if @user != current_user
      redirect_to root_path
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    params[:user][:topic_ids].each do |a|
      @user.topics << a
    end


    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    # UNCOMMENT THIS
    response = HTTParty.post("http://usapisandbox.fgdev.net/cardonfile", 
      {:body => {"accountName" => "Demo User", "ccNumber" => "4457010000000009", "ccType" => "VI", "ccExpDateMonth" => "01", "ccExpDateYear" => "18", "billToAddressLine1" => "1 Main St", "billToCity" => "Burlington", "billToState" => "MA", "billToZip" => "01803", "ccCardValidationNum" => "150", "billToFirstName" => "Demo", "billToLastName" => "User", "billToCountry" => "US", "billToEmail" => "demo@givebyone.com", "remoteAddr" => "127.0.0.1"}, 
       :headers => {"JG_APPLICATIONKEY" => ENV['JG_APPLICATIONKEY'], "JG_SECURITYTOKEN" => ENV['JG_SECURITYTOKEN']}})
    p response.parsed_response["firstGivingDonationApi"]["firstGivingResponse"]["cardOnFileId"]
  
    @user.card_token = response.parsed_response["firstGivingDonationApi"]["firstGivingResponse"]["cardOnFileId"]
    respond_to do |format|
    params[:user][:topic_ids].each do |a|
      if Topic.where(id: a).count > 0
      @user.topics << Topic.find(a)
      end
    end
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :card_token)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div id="user-form">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :topic %>
    <%= f.select :topic_ids, Topic.all.collect {|x| [x.topic, x.id]}, {}, :multiple => true, class: "topic-select" %>

  </div>
    <%= label_tag :ccNumber, "Credit Card Number: " %><%= number_field_tag :ccNumber %>
  <%= label_tag :ccType, "Credit Card Type: " %><%= text_field_tag :ccType %>
  <%= label_tag :ccExpDateMonth, "Expiration Date Month: " %><%= number_field_tag :ccExpDateMonth %>
  <%= label_tag :ccExpDateYear, "Expiration Date Year: " %><%= number_field_tag :ccExpDateYear %>
  <%= label_tag :ccCardValidationNum, "Validation Number: " %><%= number_field_tag :ccCardValidationNum %>
  <%= label_tag :accountName, "Name on Card: " %><%= text_field_tag :accountName %>
  <%= label_tag :billToFirstName, "First Name of Billing Account Holder: " %><%= text_field_tag :billToFirstName %>
  <%= label_tag :billToLastName, "Last Name: " %><%= text_field_tag :billToLastName %>
  <%= label_tag :billToAddressLine1, "Billing Address Line 1: " %><%= text_field_tag :billToAddressLine1 %>
  <%= label_tag :billToCity, "City: " %><%= text_field_tag :billToCity %>
  <%= label_tag :billToState, "State: " %><%= text_field_tag :billToState %>
  <%= label_tag :billToZip, "Billing Zip Code: " %><%= number_field_tag :billToZip %>
  <%= label_tag :billToCountry, "Country: " %><%= text_field_tag :billToCountry %>
  <%= label_tag :billToEmail, "Email: " %><%= email_field_tag :billToEmail %>
  <%= hidden_field_tag :remoteAddr, value: "127.0.0.1" %>
  
    <%= f.submit "Add account info", class: "button expand" %>
  

<% end %>
</div>

app/views/users/_pay.html.erb
<%= form_tag donate_path, method: :post do %>
	<%= hidden_field_tag :nonprof, nonprofit.uuid %>
	<%= hidden_field_tag :nonprofit, nonprofit.id %>
	<%= hidden_field_tag :user, current_user.id %>
	<%= submit_tag "Donate", class: "button expand"%>
<% end %>

app/views/users/edit.html.erb
<h1>Add interests to make your profile more complete</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<style>
  #parallaxbg, #parallaxbg2{
    /*height:100vh;*/
    position:absolute;
  }
  #landingpageheader, #scenetwo, #scenethree{
    position: relative;
    /*background-attachment: fixed;*/
  }
  /*fixed to original bg*/
  /*#dollars{
    height:300px;
  }*/



  /*what's pinned to moving parallaxbg*/
  #logo, #abouttext{
    /*position:absolute;*/
    position: relative;
    text-align: center;
    top:10vh;
    width:100vw;
  }
  #abouttext, #descriptor, #sitetitle, #linkcolor{
    color:white;
    /*font-weight: 100;*/
    /*font-family: Helvetica;*/
  }
  #descriptor, #sitetitle{
    position: relative;
  }
  #sitetitle{
    /*font-weight: 900;*/
    font-family: 'Leckerli One', cursive;
    font-size: 70px;
  }
  #aboutlogo{
    background: image-url('bench.jpg');
    -webkit-background-clip: text;
    -webkit-text-fill-color: white;
  }
  #aboutcontainer{

    /*max-width: 600px;*/
    /*margin: 0 auto;*/
    position: absolute;
    width:100vw;

  }
  #abouttext{
    max-width: 600px;
    position: relative;
    margin: 0 auto;
    text-align: left;
  }
  /*#fullwidth{
    text-align: center;
  }*/
  #contactinfo{
    /*margin-top: 30vh;*/
    position: relative;
    padding:0;
    margin:0;
    text-align:center;
    visibility: none;
    top:5vh;
  }
  .link-container{
    position: relative;
    text-align: center;
    top:80px;
    /*width:200px;*/
    font-size: 20px;
    /*margin:0 auto;*/
    /*bottom:0;
    position:absolute;*/
  }
  #signup, #signin{
    display: inline-block;
    color:white;
    border:1px solid white;
    padding:20px;
    /*float:left;*/
  }
  #signup:hover, #signin:hover{
    color:rgba(0,0,0,1);
    border: 1px solid rgba(0,0,0,1);
  }
  .spacer{
    height:300px;
    width:100%;
    background:black;
  }
</style>

<body class="root-page">
  <% if user_signed_in? %>
    <%= render '/nav' %>
  <% end %>

  <!-- slide 1 -->
  <div id="landingpageheader">
    <div id="parallaxbg"></div>
    <!-- <div id="fullwidth">
      <img src=<%= asset_path "dollar-bills.png"%> id="dollars">
    </div> -->
    <div id="logo">
      <h2 id="sitetitle">Five For Today</h2>
      <h5 id="descriptor">Give $5 to One Non-profit with just a click, as many times as you want</h5>
    </div>

    <div class="link-container">
      <% if !user_signed_in? %> 
        
          <%= link_to "Sign Up", new_user_registration_path, id: "signup" %>
        
          <%= link_to "Sign In", new_user_session_path, id: "signin" %> 
      <% end %>
    </div>
  </div>

  <!-- <div class="spacer"></div> -->

  <!-- slide 2 -->
  <div class="aboutdiv" id="scenetwo">
  <div id="parallaxbg2"></div>
  <div id="aboutcontainer">
    <h4 class="nomargins" id="abouttext">By curating a list of nonprofits, based specifically on your personal interests, <span class="lobster" id="aboutlogo">Five For Today</span> aims to make giving to a nonprofit you believe in, as easy as pressing a button. And hey, its just a dollar!</h4>
  </div>
  </div>

  <!-- <div class="spacer"></div> -->


  <!-- slide 3 -->
  <div id="scenethree">
    <h2 id="contactinfo"><a id="linkcolor" href="mailto:bellamysmith1@gmail.com">Have Questions? Contact Us!</a></h2>
  </div>




<script>
  var controller = new ScrollMagic();
  // parallax
  // new ScrollScene({
  //     triggerElement: "#landingpageheader",
  //     // speed of items pinned on parallax bg
  //     duration: $(window).height() + 150,
  //     offset: -150
  //   })
  //   .addTo(controller)
  //   .triggerHook("onCenter")
  //   .setTween(new TimelineMax().add([
  //     TweenMax.fromTo("#logo", 1, {scale: 1, alpha: 1, top: "80%"}, {top: "0%", ease: Linear.easeNone}),
  //     TweenMax.to("#parallaxbg", 1, {backgroundPosition: "0 -260%", ease: Linear.easeNone})
  //   ]));

  // parallax
  new ScrollScene({
    triggerElement: "#scenetwo",
    duration: $(window).height() + 150,
    offset: -150 
  })
  .addTo(controller)
    .triggerHook("onCenter")
    .setTween(new TimelineMax().add([
      // first top refers to the center point
      TweenMax.fromTo("#aboutcontainer", 1, {scale: 1, alpha: 1, top: "60%"}, {top: "-10%", ease: Linear.easeNone}),
      TweenMax.to("#parallaxbg2", 1, {backgroundPosition: "0 -260%", ease: Linear.easeNone})
    ]));
  




  var sceneOptions = {duration: 300, offset: -300};
  var element = $("#contactinfo");

  // fade
  new ScrollScene(sceneOptions)
    .addTo(controller)
    .triggerHook("onCenter")
    .triggerElement(element)
    .setTween(TweenMax.from(element, 1, {autoAlpha: 0}));
        
</script>



</body>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<style type="text/css">
	#dashheader{
		font-family: 'Leckerli One', cursive;
	}
	.otherfont{
		font-family: Helvetica;
		font-weight: 100;
		font-size: 16px;
	}
	.user-show-header{
		/*background-color: none;*/
		margin-top: 50px;
		height:auto;
	}
	.user-show-page{
		/*background-color: rgba(76,152,244,1);;*/
	}
	.button{
		/*border-radius: 50%;*/
	}
	.user-topics, .user-donations, .user-feed{
		/*border-color: rgba(130,180,250,1);*/
		/*border-radius: 5px;*/
	}
	.inline-block{
		display: inline-block;
	}
</style>


<body class="user-show-page">
<% if user_signed_in? %>
  <%= render '/nav' %>
<% end %>
<div class="user-show-header">

	<h2 id="dashheader">Five For Today <span class="otherfont">Dashboard</span></h2>
</div>


<div class="user-topics large-7 columns">
	<h3 class="inline-block"> Your Topics</h3>
	<%= link_to "Add Topics", edit_user_path(@user), :class => "inline-block" %>
	<div>
	<% @user.topics.each do |a| %>
		<p class="button"><%= a.topic %></p>
	<% end %>
	</div>

	
</div>

<div class="user-donations large-4 columns">
	<h3>YOUR DONATIONS:</h3>
	<p>Total Donations: <%= @user.donations.count %></p>
</div>

<div class="user-feed large-7 columns">
	<% @user.interested.shuffle.each do |n| %>
	  <div class="feed-item">
	  	<h6 class="topic" align="right"><%= n.main %></h6>
	  	<h6><%= link_to n.name, profile_path(n) %></h6>
	  	<div class="dollar-tweet">
	  		<p class="where">Where will your dollar go?</p>
	  		<p class="item-description"><%= n.description %><p>
	  	</div>
	  	<%= render 'users/pay', :nonprofit => n %>
	  </div>
	<% end %>
</div>
</body>