config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  root 'users#index'
  
 

  resources :users
  get '/nonprofits/:id/profile' => 'nonprofits#profile', as: :profile
  
  post 'nonprofits' => 'donations#create', as: :donate
  post 'nonprofits/new' => 'nonprofits#create', as: :new_nonprofit_path
  resources :nonprofits

end

app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :donations
  has_many :users, through: :donations
  has_many :topicJunctionTables
  has_many :topics, through: :topicJunctionTables

  

  def main
  	Topic.find(self.main_topic.to_i).topic
  end
  



end

app/controllers/nonprofits_controller.rb
class NonprofitsController < ApplicationController
  before_action :set_nonprofit, only: [:show, :edit, :update, :destroy]

  # GET /nonprofits
  # GET /nonprofits.json
  def index
    @nonprofits = Nonprofit.all.shuffle
    @featured = Nonprofit.all.sample  
    @all_donations = []
    Nonprofit.all.each do |n|
      @all_donations << { 'nonprofit' => n.name, 'donations' => n.donations.count}
    end
    respond_to do |format|
          format.html {@nonprofits = Nonprofit.all.shuffle}
          format.json { render :json => {data: [@all_donations]} }
    end

  end

  # GET /nonprofits/1
  # GET /nonprofits/1.json
  def show
    @donation_count =  @nonprofit.donations.count

    dates = []
    @nonprofit.donations.each do |a|
      dates << a.created_at.day
    end
    @donations = []
    @donations_by_date = []

      for i in (0..6) 
        date = Date.today - i
        @donations << date
      end

      @donations.reverse.each do |a|
        @donations_by_date << { 'date' => a, 'donations' => dates.count(a.day)} if !@donations_by_date.include?({  'date' => a, 'donations' => @donations.count(a)})
      end
    @all_donations = []
    Nonprofit.all.each do |n|
      @all_donations << { 'nonprofit' => n, 'donations' => n.donations.count}
    end
      
    respond_to do |format|
          format.html {@user = Nonprofit.find(params[:id])}
          format.json { render :json => {data: [@donations_by_date, @all_donations]} }
    end
  end

  # GET /nonprofits/new
  def new
    unless current_user.email == "admin@givebyone.com"
      redirect_to root_path
    end
    @nonprofit = Nonprofit.new
  end

  def profile
    @nonprofit = Nonprofit.find(params[:id])
  end

  # GET /nonprofits/1/edit
  def edit
    unless current_user.email == "admin@givebyone.com"
      redirect_to root_path
    end
  end

  # POST /nonprofits
  # POST /nonprofits.json
  def create

    @nonprofit = Nonprofit.new(nonprofit_params)
      #There is a blank id with the multiple select field, so I have to go through and push them individually into the Nonprofit's topics
      params[:nonprofit][:topic_ids].each do |a|
        if Topic.where(id: a).count > 0
          @nonprofit.topics << Topic.find(a)
        end
      end
      #main topic param needs to be changed to an integer:
      @nonprofit.main_topic = params[:nonprofit][:main_topic].to_i
    respond_to do |format|
      if @nonprofit.save
        format.html { redirect_to @nonprofit, notice: 'Nonprofit was successfully created.' }
        format.json { render :show, status: :created, location: @nonprofit }
      else
        format.html { render :new }
        format.json { render json: @nonprofit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nonprofits/1
  # PATCH/PUT /nonprofits/1.json
  def update
    unless current_user.email == "admin@givebyone.com"
      redirect_to root_path
    end
    respond_to do |format|
      #Delete all of the topics to update with new ones
      @nonprofit.topics.delete_all
      #There is a blank id with the multiple select field, so I have to go through and push them individually into the Nonprofit's topics
      params[:nonprofit][:topic_ids].each do |a|
        if Topic.where(id: a).count > 0
          @nonprofit.topics << Topic.find(a)
        end
      end
      #main topic param needs to be changed to an integer:
      @nonprofit.main_topic = params[:nonprofit][:main_topic].to_i

      if @nonprofit.update(nonprofit_params)
        format.html { redirect_to nonprofit_path(@nonprofit), notice: 'Nonprofit was successfully created!' }
        format.json { render :show, status: :ok, location: @nonprofit }
      else
        format.html { render :edit }
        format.json { render json: @nonprofit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nonprofits/1
  # DELETE /nonprofits/1.json
  def destroy
    unless current_user.email == "admin@givebyone.com"
      redirect_to root_path
    end
    @nonprofit.destroy
    respond_to do |format|
      format.html { redirect_to nonprofits_url, notice: 'Nonprofit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nonprofit
      @nonprofit = Nonprofit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nonprofit_params
      params.require(:nonprofit).permit(:name, :email, :description, :website, :city, :state, :phone, :topic_id, :main_topic, :ein, :logo, :uuid)
    end
end

app/helpers/nonprofits_helper.rb
module NonprofitsHelper
end

app/views/nonprofits/_form.html.erb
<%= form_for @nonprofit, :url => new_nonprofit_path do |f| %>
  <% if @nonprofit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nonprofit.errors.count, "error") %> prohibited this nonprofit from being saved:</h2>

      <ul>
      <% @nonprofit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="np-name field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="np-website field">
    <%= f.label :website %>
    <%= f.url_field :website %>
  </div>
  <div class="np-phone field">
    <%= f.label :phone %>
    <%= f.telephone_field :phone %>
  </div>
   <div class="np-city field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
   <div class="np-state field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="np-description field">
    <%= f.label :description, 'Description: (A sentence or two answering the questions "What will the dollar go toward?" 255 Characters Max.)' %><br>
    <%= f.text_area :description %>
  </div>
  <div class="np-main field">
    <%= f.label :main_topic %>
    <%= f.collection_select :main_topic, Topic.all, :id, :topic %>
  </div>
  <div class="np-topics field">
    <p>Choose the topics that your non-profit covers. If you do not choose at least one topic, your non-profit will not be featured on user pages (Maximum 5)</p>
    <%= f.label :topic, "Hold Ctrl/Cmd to select multiple topics" %>
    <%= f.select :topic_ids, Topic.all.collect {|x| [x.topic, x.id]}, {}, :multiple => true, class: "topic-select" %>

  </div>
  <%= f.hidden_field :logo %>
  <%= f.hidden_field :ein %>
  <%= f.hidden_field :uuid %>


  <div class="actions">
    <%= f.submit "Continue and Finish", class: "button expand"%>
  </div>
 
<% end %>

app/views/nonprofits/edit.html.erb
<body class="edit-nonprofit-page">
<header id="edit-nonprofit-header">
<h1>Step 2:</h1>
<h4>Please enter your nonprofit's information below so we can better connect users to your profile. By choosing topics that accurately reflect your mission, our users will be more willing to click the Donate button!</h4>
</header>
<div class="edit-nonprofit-form">
	<%= render 'form' %>
</div>

</body>

app/views/nonprofits/index.html.erb
<body class="home-page">
    <% if user_signed_in? %>
      <%= render '/nav' %>
    <% end %>
  <header class="home-header">
    <% if !user_signed_in? %>
      <%= link_to "Sign In", new_user_session_path %> 
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </header>

  <div class="home-container">
    <div class="featured-nonprofit">
        <h2>Featured:</h2>
       
      
        <div class="padding">
          <h4><%= @featured.main %></h4>
      
    
           
          <h3 class="nonprofit-title"><%= link_to @featured.name, profile_path(@featured) %></h3>
          
        
          <a class="nonprofit-website" href="<%=@featured.website %>"><%= @featured.website %></a>
          <h4 class="nonprofit-description"><%= @featured.description %></h4>
      
          <%= render 'users/pay', :nonprofit => @featured %>
          
      </div>
          
      <!--For the screen shot image -->
      <script> var p2i=new page2images(); p2i.thumbnail('demo');</script>

   </div>   
 <div class="nonprofit-container"> 
  <div class="color-title">
  <h2>All-Topics<h2>
    <h5>Browse and donate to all of the nonprofits on Give One to One</h5>
     </div>
    <% @nonprofits.each do |a| %>

    <div class="nonprofit">
      <p class="nonprofit-topic"><%= a.main %></p>
      <h6 class="nonprofit-title"><%= link_to a.name, profile_path(a) %></h6>
      <h6 class="nonprofit-description"><%= a.description%></h6>
 
      <%= link_to "See More", nonprofit_path(a) %>
      <%= render 'users/pay', :nonprofit => a %>
      
    </div>
    <% end %>
</div>

  </div>
  <div class="d3">
  </div>

</body>

app/views/nonprofits/new.html.erb
<h1>New nonprofit</h1>
<div class="EIN-form">
	<input id="nonprofit-tax-id" type="text">
</div>
<div class="nonprofit-form">
<%= render 'form' %>
</div>
<%= link_to 'Back', nonprofits_path %>

app/views/nonprofits/profile.html.erb
<% if user_signed_in? %>
	<%= render '/nav' %>
<% end %>
<body class="profile-page">
	<a href="/">
	<header class="sign-up-header">
		<img src=<%= asset_path 'dollar-bills.png' %>>
		<h2 align="center">Give By One</h2>

	</header>
</a>
<div class="nonprofit-block">
<div class="title-head">	
<h1><%= @nonprofit.name %></h1>
<h4><%= @nonprofit.city.capitalize %>, <%= @nonprofit.state.upcase %></h4>
<a href=<%= @nonprofit.website %>><%= @nonprofit.website %></a>
<br>
</div>
<div class="profile-body">
<h5>What will your dollar go toward?</h5>
<h6 class="description"><%= @nonprofit.description %></h6>
<div class="row">

</div>
<div class="topic-list">
<h5 align="center" >Main Topic: </h5>
	<h6 align="center"><%= @nonprofit.main %></h6>
<h5 align="center">General Topics</h5>
<h6><% @nonprofit.topics.distinct.each do |t| %>
	<%= t.topic %>, 
<% end %>
</h6>
</div>
</div>
</div>
<footer class="profile-footer">
	<h6>Contact Us! We need your feedback!</h6>
</footer>
</body>

app/views/nonprofits/show.html.erb
<body class="nonprofit-show-page">


<p id="notice"><%= notice %></p>

<header id="nonprofit-show-header">
	<h2>Give One to One</h2>
</header>
<main class="np-show-container">
<div class="nonprofit-info">
<h6><%= @nonprofit.name %>'s Account Info</h6>
<div class ="row">
	<div class="large-4 columns">
 		<p align="left"><strong>Name:</strong>
  		<%= @nonprofit.name %></p>
	</div>
	<div class="large-4 columns">
  		<p align="center"><strong>Website:</strong>
  		<%= @nonprofit.website %></p>
	</div>
	<div class="large-4 columns">
  		<p align="right"><strong>Phone:</strong>
  		<%= @nonprofit.phone %></p>
	</div>

</div>
<div class="row">
	<div class="large-12 columns" id="description">
		<p>What will the dollar go toward?</p>
		<p><%= @nonprofit.description %></p>
	</div>
</div>
<div class="row">
	<p align="right" id="edit-nonprofit-link"><%= link_to 'Edit Your Nonprofit Info', edit_nonprofit_path(@nonprofit) %></p>
</div>

</div>
<div class="row">
<div class="donations large-8 columns">
	<h6>Donations</h6>
	<p align="center">Total Donations: <%= @nonprofit.donations.count %></p>
	
</div>

<div class="topics large-3 columns">
	<h6>Topics:</h6>
	<div class="topic-body">
		<p align="center"><%= @nonprofit.main %></p>
	<% @nonprofit.topics.distinct.each do |a| %>
		<p align="center"><%= a.topic %></p>
	<% end %>
</div>
</div>
</div>

</main>
<div class="root-footer">
  <a href="mailto:bellamysmith1@gmail.com">Have Questions? Contact Us!</a>
</div>

</body>